Add Symfony 7 support
sulu/SuluCommentBundle pull request #53
Opened 2024-05-29 04:44 UTC by TheCadien

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #[issuenum](https://github.com/sulu/sulu/issues/7413)
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?
Add Symfony 7 support

#### Why?

is cool

2024-06-03 08:49 UTC, Prokyonn requested changes

2024-06-03 08:49 UTC, Prokyonn commented on composer.json
> +        "php": "^8.2 || ^8.3",
Should also match the sulu 2.5 requirements ^8.0/^8.1

Therefore also the CI should run for these php versions

2024-06-10 09:01 UTC, alexander-schranz commented on composer.json
> +        "symfony/config": "^5.4 || ^6.0 || ^7.0",
if not required I woul d keep the `^4.4`

2024-06-10 09:02 UTC, alexander-schranz commented on composer.json
> +        "sulu/sulu": "^2.5 || ^2.6@dev",
if not required I would keep the lower version

2024-07-19 10:13 UTC, alexander-schranz requested changes
Check `composer outdated` output and check that things like jackalope are also upgraded else you will not get Symfony 7 compatibility in the test run see output:


![Bildschirmfoto 2024-07-19 um 12 11 51](https://github.com/user-attachments/assets/af30680b-7527-4ef6-b893-4053a2ee4184)
t of `composer info`:

2024-07-24 17:06 UTC, merged